; --------------------------------------------------------------------
; Skyscraper by Lars Muldjord (https://github.com/Gemba/skyscraper)
; --------------------------------------------------------------------

; extended documentation: https://gemba.github.io/skyscraper/CONFIGINI/
[main]
frontend="pegasus"
; ~ expansion to $HOME only works on Linux
inputFolder="~/Games"
videos="true"
symlink="true"

[pegasus]
;gameListFilename=metadata.pegasus.txt
; global for all systems
;launch=...

;[gba]
; per system launch command
;launch=...

;[nds]
; per system launch command
;launch=...

;[snes]
; per system launch command
;launch=...
